# Page settings

baseurl = ""
languageCode = "en-us"
title = "Tenny Vongtip Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Pavel Kanyshev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Siriwat (Tenny) Vongtip"
        tagline = "Network Engineer"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: tenny.vongtip@gmail.com"
        title = "Tenny Vongtip"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+12104289096"
        title = "+210-428-9096"

    #   [[params.contact.list]]
      #  class = "website"
       # icon = "fa-globe"
       # url = "//portfoliosite.com"
       # title = "portfoliosite.com"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/siriwat-vongtip"
        title = "linkedin.com/in/Tenny"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/TennyV"
        title = "github.com/TennyV"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/tennyv"
        title = "@TennyV"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "B.P.S. in Computer Programming"
        college = "Syracuse University"
        dates = "2023 - 2025"
        
        [[params.education.list]]
        degree = "B.S. in Computer Science"
        college = "Southern New Hampshire University"
        dates = "2021-2023"
        
    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Native"

        [[params.language.list]]
        language = "Thai"
        level = "Conversational"

       # [[params.language.list]]
       # language = "Russian"
       # level = "Professional"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Embedded technologies"

        [[params.interests.list]]
        interest = "Raspberry Pi"

        [[params.interests.list]]
        interest = "Fly fishing"

        [[params.interests.list]]

        interest = "Rock Climbing"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "Hello, I am a network engineer with over 10 years of experience. I am a dedicated lifelong student, continuously seeking opportunities to enhance my expertise and adeptly tackle complex challenges. As a proactive individual, I take ownership of my responsibilities and consistently strive to help my team achieve excellence. My passions lie in networking and software development. I am dedicated to delivering top-quality products and solutions, and am excited for the opportunity to collaborate with your team to drive exceptional results."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experience"

        [[params.jobs.list]]
        position = "Cyber Security Auditor intern"
        dates = "May 2023 - Present"
        company = "United Services Automobile Association(USAA)"
        details = "In this role, I created supporting technical documents that drove forward the design and operating effectiveness of various controls related to the integration, monitoring, and reporting of information indicative of internal threats. \n \n Updated process maps that identified business partner workflows that highlight technologies within the Internal Threat Management engagement, the work produced highlighted controls that require further refinement and opportunities for improvement."
        

        [[params.jobs.list]]

        [[params.jobs.list]]
        position = "Systems Administrator"
        dates = "December 2022 - May 2023"
        company = "Piedmont Regional Council, Kernersville, NC"
        details = " In this role, I expertly developed and implemented custom business solutions using Microsoft PowerApps. These solutions included automation of business processes and data visualization dashboards, which helped drive more informed business decisions and boost productivity for various departments within the organization. \n \n Additionally, I successfully managed and administered the Azure cloud infrastructure for an organization of 200 people, including the deployment, configuration, and maintenance of virtual machines, storage, and network resources, resulting in increased scalability and security for the organization. "

        [[params.jobs.list]]
        position = "Information Technology Support Administrator"
        dates = "December 2021 - December 2022"
        company = "10th Mountain Divsion, Fort Drum, NY"
        details = "While serving in this position, I developed and designed a musical group request form using CSS and HTML. This form allowed users to easily request musical support and view upcoming performances, resulting in increased engagement and satisfaction for the organization. \n \n As a champion for advocating workflows, I analyzed organizational workflows and took our processes to the next level by building a cloud-based architecture that provided real-time updates that boosted productivity by over 50%."


        [[params.jobs.list]]
        position = "Director of Plans and Operations"
        dates = "January 2021 - December 2021"
        company = "10th Mountain Division, Fort Drum, NY"
        details = "In this role I was responsible for developing and executing plans, operations, and training for a 40 employee organization. Our organization was responsible for providing musical and logistical support to over 17,000 families and civilians in Upstate NY. \n \n I developed a strategy for digital marketing, developed a vision and represented the unit director at meetings at the local and corporate levels; I prepared reports and made recommendations to the Deputy CEO following research on maximizing the returns on investment."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "I enjoy tinkering and combining electricity and programming. In my alternative life I'd been a computer engineer as I have developed a hobby of building IOT devices. I truly just enjoy technology and hope you like what you see!"

        [[params.projects.list]]
        title = "Inventory Management Application"
        url = "https://github.com/TennyV/inventory_Management"
        tagline = "The goal of this project was to design an Android inventory management application in Java with the ability to store users,inventory items, and quantities in an SQLite database."

        [[params.projects.list]]
        title = "Dash visualization dashboard for Animal Shelter"
        url = "https://github.com/TennyV/AAC_shelter"
        tagline = "Simple application for tracking animals within the animal shelter utilizing the dash application connecting a python module with my REST API with mongodb and proofing work in jupyter notebooks"

        [[params.projects.list]]
        title = "Open Access JPMorgan Chase Virtual experience"
        url = "https://github.com/TennyV/JPMorgan"
        tagline = "Analyze Datasets of Fraud in Financial Payments – Utilized Python and pandas’ library to analyze a large dataset. Created visualizations within Jupyter notebook to assist and to make better-informed business decisions."

        [[params.projects.list]]
        title = "OWASP Vulnerability Report/Suppression of False Positives"
        url = "https://github.com/TennyV/OWASPremedy"
        tagline = "Set up IntelliJ environment to scan for vulnerabilities within banking app (with permission). Detected occurrences of bouncy house and identified and remediated false positives. Recommended the update of spring-boot and refactoring to ensure security and functionality. Testing and control design was paramount to this project."

        [[params.projects.list]]
        title = "Shopping Cart"
        url = "https://github.com/TennyV/Shoppingcart"
        tagline = "My shopping cart project takes a text file and produces a list that outputs three things. A list of all produce and number of produce that was sold that day. A list of a specific item and how many times it was purchased in one day and a histogram of all produce items purchased on a particular day."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills"

        [[params.skills.list]]
        skill = "Python"
       # level = "60%"
                
        [[params.skills.list]]
        skill = "MongoDB"
       # level = "70%"

        [[params.skills.list]]
        skill = "Angular"
       # level = "40%"

        [[params.skills.list]]
        skill = "HTML5 & CSS"
       # level = "80%"

        [[params.skills.list]]
        skill = "Java"
      #  level = "75%"

        [[params.skills.list]]
        skill = "C/C++"
       # level = "50%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Ported for Tenny Vongtip"
