# Page settings

baseurl = ""
languageCode = "en-us"
title = "Tenny Vongtip - Cybersecurity Professional"
theme = "hugo-orbit-theme"
# googleAnalytics = "UA-XXXXXXX-Y"

# Professional site settings
enableGitInfo = true
enableEmoji = true
enableRobotsTXT = true

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Pavel Kanyshev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Siriwat (Tenny) Vongtip"
        tagline = "Cybersecurity Specialist & Technology Strategist"
        avatar = "profile-new.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: tenny.vongtip@gmail.com"
        title = "Tenny Vongtip"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+48 722 338 040"
        title = "+48 722 338 040"

    #   [[params.contact.list]]
      #  class = "website"
       # icon = "fa-globe"
       # url = "//portfoliosite.com"
       # title = "portfoliosite.com"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/siriwat-vongtip"
        title = "linkedin.com/in/Tenny"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/TennyV"
        title = "github.com/TennyV"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/tennyv"
        title = "@TennyV"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Masters in Information Security Engineering"
        college = "SANS Technology Institute"
        dates = "2023 - 2026"
        
        [[params.education.list]]
        degree = "Bachelor of Science in Computer Science"
        college = "Southern New Hampshire University"
        dates = "2021-2023"

    # Certifications section
    [params.certifications]
        enable = true
        title = "Certifications"

        [[params.certifications.list]]
        name = "GIAC Web Application Penetration Tester (GWAPT)"
        issuer = "GIAC"
        date = "September 2025"

        [[params.certifications.list]]
        name = "GIAC Security Essentials (GSEC)"
        issuer = "GIAC"
        date = "May 2023"

        [[params.certifications.list]]
        name = "GIAC Certified Incident Handler (GCIH)"
        issuer = "GIAC"
        date = "August 2023"

        [[params.certifications.list]]
        name = "GIAC Certified Intrusion Analyst (GCIA)"
        issuer = "GIAC"
        date = "November 2023"

        [[params.certifications.list]]
        name = "GIAC Strategic Planning, Policy & Leadership (GSTRT)"
        issuer = "GIAC"
        date = "May 2024"

        [[params.certifications.list]]
        name = "GIAC Defense Security Architecture (GDSA)"
        issuer = "GIAC"
        date = "January 2025"

        [[params.certifications.list]]
        name = "GIAC Cloud Security Automation (GCSA)"
        issuer = "GIAC"
        date = "March 2025"

        [[params.certifications.list]]
        name = "CompTIA A+"
        issuer = "CompTIA"
        date = "December 2021"
        
    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Native"

        [[params.language.list]]
        language = "Thai"
        level = "Conversational"

       # [[params.language.list]]
       # language = "Russian"
       # level = "Professional"



    # Interests section
    [params.interests]
        enable = true
        title = "Professional Interests"

        [[params.interests.list]]
        interest = "Cybersecurity Research"

        [[params.interests.list]]
        interest = "Cloud Security Architecture"

        [[params.interests.list]]
        interest = "Network Security Engineering"

        [[params.interests.list]]
        interest = "IoT Security"

        [[params.interests.list]]
        interest = "Threat Intelligence"

        [[params.interests.list]]
        interest = "Security Automation"

    # Blog section
    [params.blog]
        enable = true
        title = "Latest Blog Posts"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Professional Summary"
        summary = "Experienced Cybersecurity Specialist with over 10 years of IT expertise, specializing in cloud security, threat management, and compliance frameworks. Based in Poznan, Poland, I bring a global perspective to cybersecurity challenges while serving clients across Europe and beyond. Proven track record of implementing security controls, reducing vulnerabilities, and enhancing organizational cyber maturity. Skilled in Azure cloud infrastructure, Microsoft Power Platform automation, and security auditing. Passionate about continuous learning and delivering innovative solutions that drive business excellence."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experience"

    # Jobs section
    [params.jobs]
        enable = true

        [[params.jobs.list]]
        position = "IT Cybersecurity Specialist"
        dates = "July 2024 - Present"
        company = "Department of the Interior"
        details = "• Enhanced cybersecurity governance framework, achieving 95%+ compliance across 7 systems (3 medium-risk, 4 low-risk)\n\n• Led AI-driven cybersecurity awareness program, reducing content creation time by 50% and increasing phishing reporting by 60%\n\n• Conducted comprehensive audit of 10,000+ Azure accounts, identifying and remediating 3% unauthorized access in Microsoft Entra ID\n\n• Developed automated workflows using Microsoft Power Platform, reducing document processing time by 80%\n\n• Orchestrated business continuity planning for critical systems, identifying and resolving backup plan discrepancies\n\n• Championed DevSecOps initiatives by integrating automated security scanning (SAST/SCA) into CI/CD pipelines on Azure DevOps and GitHub Actions, resulting in the discovery of 40+ critical vulnerabilities and the adoption of safer dependency management by development teams"

        [[params.jobs.list]]
        position = "IT/Cyber Security Auditor"
        dates = "January 2024 - July 2024"
        company = "United Services Automobile Association (USAA)"
        details = "• Developed comprehensive technical documentation for internal threat management controls and monitoring systems\n\n• Created detailed process maps identifying business partner workflows and technology integration points\n\n• Analyzed control effectiveness and identified opportunities for refinement and improvement\n\n• Collaborated with cross-functional teams to enhance security posture and threat detection capabilities"

        [[params.jobs.list]]
        position = "Systems Administrator"
        dates = "December 2022 - May 2023"
        company = "Piedmont Regional Council, Kernersville, NC"
        details = "• Developed and deployed custom Microsoft PowerApps solutions, automating business processes and creating data visualization dashboards\n\n• Managed Azure cloud infrastructure for 200+ users, including VM deployment, storage configuration, and network resource maintenance\n\n• Enhanced organizational productivity through streamlined workflows and improved decision-making capabilities\n\n• Implemented security best practices and ensured system scalability and reliability"

        [[params.jobs.list]]
        position = "Systems Administrator"
        dates = "December 2012 - December 2022"
        company = "Various locations in the US and overseas"
        details = "• Managed critical infrastructure including Windows systems, LAN networks, and cloud backup solutions\n\n• Supervised application maintenance and computing infrastructure activities ensuring 99.9% uptime\n\n• Provided technical support to 200+ employees across the United States with <2-hour response times\n\n• Implemented robust backup and disaster recovery procedures ensuring data resilience and availability\n\n• Provided Tier 1/2 technical support for over 500 personnel, resolving an average of 200+ helpdesk tickets monthly with a 87% satisfaction rating\n\n• Managed user accounts, permissions, and group policies within Active Directory to ensure compliance with strict Department of Defense (DoD) security protocols"

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Technical Projects"
        intro = "A collection of projects demonstrating expertise in cybersecurity, software development, and data analysis. These projects showcase practical applications of security principles, automation, and analytical thinking."

        [[params.projects.list]]
        title = "Inventory Management Application"
        url = "https://github.com/TennyV/inventory_Management"
        tagline = "Developed a comprehensive Android inventory management system using Java and SQLite database, featuring user authentication, real-time inventory tracking, and data persistence capabilities."

        [[params.projects.list]]
        title = "Animal Shelter Analytics Dashboard"
        url = "https://github.com/TennyV/AAC_shelter"
        tagline = "Built an interactive data visualization dashboard using Python Dash framework, integrating REST API with MongoDB for real-time animal shelter data tracking and analytics."

        [[params.projects.list]]
        title = "Financial Fraud Detection Analysis"
        url = "https://github.com/TennyV/JPMorgan"
        tagline = "Conducted comprehensive fraud analysis on financial payment datasets using Python and pandas, creating data visualizations and statistical models to identify patterns and support risk management decisions."

        [[params.projects.list]]
        title = "OWASP Security Vulnerability Assessment"
        url = "https://github.com/TennyV/OWASPremedy"
        tagline = "Performed comprehensive security assessment of banking application using IntelliJ and OWASP tools, identifying vulnerabilities, remediating false positives, and recommending security improvements including Spring Boot updates."

        [[params.projects.list]]
        title = "Data Analytics Shopping Cart System"
        url = "https://github.com/TennyV/Shoppingcart"
        tagline = "Developed a data processing system that analyzes sales data from text files, generating comprehensive reports including product sales summaries, item-specific analytics, and visual histograms for business intelligence."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Technical Skills & Proficiencies"

        [[params.skills.list]]
        category = "Cybersecurity & Security Tools"
        skills = "Threat Management, Security Auditing, Compliance Frameworks (NIST, ISO 27001), Vulnerability Assessment, Incident Response, Security Controls, OWASP ZAP, Penetration Testing, Risk Assessment, Security Scanners, IntelliJ"

        [[params.skills.list]]
        category = "Cloud & Infrastructure"
        skills = "Microsoft Azure, AWS, Cloud Security, Infrastructure Management, Virtual Machines, Network Security, Azure Active Directory, Microsoft Entra ID, Cloud Backup Solutions, Disaster Recovery"

        [[params.skills.list]]
        category = "Programming & Development"
        skills = "Python, Java, JavaScript, SQL, PowerShell, REST APIs, Microsoft Power Platform, PowerApps, Power Automate, HTML/CSS, Git, Version Control"

        [[params.skills.list]]
        category = "Data & Analytics"
        skills = "Data Analysis, Data Visualization, Pandas, Jupyter Notebooks, MongoDB, SQLite, Business Intelligence, Dashboard Creation, Statistical Analysis"

        [[params.skills.list]]
        category = "IT Management & Support"
        skills = "Windows Systems Administration, LAN/WAN Management, Technical Support, System Maintenance, User Training, Documentation, Process Automation, Change Management"

        [[params.skills.list]]
        category = "Business & Leadership"
        skills = "Strategic Planning, Project Management, Team Leadership, Stakeholder Communication, ROI Analysis, Digital Marketing, Business Process Optimization"

    # Footer section

    [params.footer]
        copyright = "Tenny Vongtip. All rights reserved."
